[URH-19] useSound 신규
frontend-opensource-project/use-react-hooks pull request #37
Opened 2024-08-02 07:10 UTC by Choozii

## 👾 Pull Request

- 티켓: [useSound 신규](https://use-react-hooks.atlassian.net/browse/URH-19)

- 상태: 신규

### 1️⃣ Spec

- 오디오를 관리해주는 Hook
  - play, pause, stop, 반복 재생 설정, 재생 위치 설정, 볼륨 설정, 배속 설정 함수 리턴
  - 오디오가 준비되었는지, 현재 볼륨, 반복 재생인지, 일시 정지 여부, 재생 여부, 오디오 길이, 현재 재생 위치 리턴

### 2️⃣ 변경 사항

### 3️⃣ 예시 코드

```ts
import useSound from './hooks/useSound';

const App = () => {
  const result = useSound({
    url: 'https://github.com/rafaelreis-hotmart/Audio-Sample-files/raw/master/sample.mp3',
  });

  const {
    volume,
    playbackRate,
    isLoop,
    duration,
    currentTime,
    play,
    pause,
    stop,
    setIsLoop,
    setPosition,
    setVolume,
    setPlaybackRate,
  } = result;

  const handleVolumeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setVolume(parseFloat(e.target.value));
  };

  const handlePlaybackRateChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPlaybackRate(parseFloat(e.target.value));
  };

  const handlePositionChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPosition(parseFloat(e.target.value));
  };

  return (
    <div>
      <button onClick={play}>재생</button>
      <button onClick={pause}>일시정지</button>
      <button onClick={stop}>정지</button>
      <div>
        <label>
          볼륨:
          <input
            type="range"
            min="0"
            max="1"
            step="0.01"
            value={volume}
            onChange={handleVolumeChange}
          />
        </label>
      </div>
      <div>
        <label>
          배속:
          <input
            type="range"
            min="0.5"
            max="2"
            step="0.1"
            value={playbackRate}
            onChange={handlePlaybackRateChange}
          />
        </label>
      </div>
      <div>
        <label>
          재생 위치:
          <input
            type="range"
            min="0"
            max={duration}
            step="0.1"
            value={currentTime}
            onChange={handlePositionChange}
          />
        </label>
      </div>
      <div>
        <label>
          반복 재생:
          <input
            type="checkbox"
            checked={isLoop}
            onChange={(e) => setIsLoop(e.target.checked)}
          />
        </label>
      </div>
    </div>
  );
};

export default App;

```

### 4️⃣ 관련 문서 (선택 사항)
- [HTML Audio Reference](https://www.w3schools.com/tags/ref_av_dom.asp)

2024-08-02 19:05 UTC, foresec reviewed
저도 노래 듣는 걸 참 좋아하는데요 그래서 이런 audio관련 훅이 더 반가운것 같습니다! 

이미 많은 기능을 제공하고 있는 훅이지만.. 코드 리뷰를 하기 전에 빠르게 기능 추가를 제안드리고 싶어 먼저 코멘트를 남겨봅니다.

1. 용도가 음악재생일 경우, `02:20 / 3:52`와 같은 형태로 활용할 수 있도록 현재재생시간, 전체재생시간을 제공 
2. 용도가 bgm재생일 경우, 음소거를 켜고 끄는 기능을 따로 제공
3. 다른 용도 ETC...

이 useSound훅을 어느 정도의 범위를 염두에 두고 만드셨나요? 일단 이렇게 제가 생각한 범위에서 필요한 기능을 더 제안드리고 싶습니다. 특히 음소거의 경우 용도가 음악재생이든, BGM이든 추가됐을 때 유용하게 쓰일 수 있는 기능이라고 생각합니다

2024-08-03 03:22 UTC, jeongbaebang reviewed
고생하셨습니다 👍

2024-08-03 03:22 UTC, jeongbaebang commented on src/hooks/useSound.ts
> +
[P2] 사운드와 관련된 여러 상태를 개별적으로 관리하고 있으며, 각 상태의 업데이트 로직도 따로 처리하고 있습니다. useReducer를 사용하여 상태를 관리하는 방식에 대해 어떻게 생각하시는지 의견을 듣고 싶습니다.

```ts
return {
  ...state, // useReducer 상태
  play,
  pause,
  stop,
  setIsLoop,
  setPosition,
  setVolume,
  setPlaybackRate,
};
```

2024-08-03 03:22 UTC, jeongbaebang commented on src/hooks/useSound.ts
> +  const safeAudioHelper = (action: SafeAudioAction) => {
[P3] audio 인스턴스가 있는지 파악하는 로직을 통해 다른 부분에서 안전하게 값에 접근하는 방식이 인상적이었습니다 👍👍
```ts
// audio element를 체크하는 헬퍼 함수
const safeAudioHelper = (action: SafeAudioAction) => {
  if (audioRef.current) {
    action(audioRef.current);
  }
};
```
다만 궁금한 점이 생겼습니다. 140-150라인을 보면 다음과 같이 작성되어 있습니다:
```ts
useEffect(() => {
  if (audioRef.current) {
    audioRef.current.volume = volume;
  }
}, [volume]);

useEffect(() => {
  if (audioRef.current) {
    audioRef.current.playbackRate = playbackRate;
  }
}, [playbackRate]);
```
위와 같은 방식 대신, 헬퍼 함수를 사용하여 audio 인스턴스의 유효성을 체크하고 다음과 같이 작성하는 것도 가능할 것 같습니다:
```ts
useEffect(() => {
  safeAudioHelper((audioRef) => {
    audioRef.volume = volume;
  });
}, [volume]);

useEffect(() => {
  safeAudioHelper((audioRef) => {
    audioRef.playbackRate = playbackRate;
  });
}, [playbackRate]);
```
이 방식이 이전과 동일하게 동작할 것 같은데, 굳이 if 문으로 분기를 하는 이유가 있는지 의견을 듣고 싶습니다.

2024-08-03 03:30 UTC, Choozii commented
> 저도 노래 듣는 걸 참 좋아하는데요 그래서 이런 audio관련 훅이 더 반가운것 같습니다!
> 
> 이미 많은 기능을 제공하고 있는 훅이지만.. 코드 리뷰를 하기 전에 빠르게 기능 추가를 제안드리고 싶어 먼저 코멘트를 남겨봅니다.
> 
> 1. 용도가 음악재생일 경우, `02:20 / 3:52`와 같은 형태로 활용할 수 있도록 현재재생시간, 전체재생시간을 제공
> 2. 용도가 bgm재생일 경우, 음소거를 켜고 끄는 기능을 따로 제공
> 3. 다른 용도 ETC...
> 
> 이 useSound훅을 어느 정도의 범위를 염두에 두고 만드셨나요? 일단 이렇게 제가 생각한 범위에서 필요한 기능을 더 제안드리고 싶습니다. 특히 음소거의 경우 용도가 음악재생이든, BGM이든 추가됐을 때 유용하게 쓰일 수 있는 기능이라고 생각합니다

1. 용도가 음악재생일 경우, 02:20 / 3:52와 같은 형태로 활용할 수 있도록 현재재생시간, 전체재생시간을 제공 -> 해당 건은 currentTime(현재 재생 위치)이랑 duration(음원 총 길이)로 나타낼 수 있을것 같아요!
2. 음소거를 켜고 끄는 기능을 따로 제공 -> 음소거! 는 생각못했는데 추가해볼게요!!! 의견 감사합니당!

2024-08-03 03:40 UTC, Choozii commented on src/hooks/useSound.ts
> +  const safeAudioHelper = (action: SafeAudioAction) => {
엇 그러네요!! 수정할게용 감사합니다!

2024-08-03 04:00 UTC, Choozii commented on src/hooks/useSound.ts
> +
좋은 생각이에용!!! 수정해볼게요우~

2024-08-03 07:12 UTC, foresec commented
> 1. 용도가 음악재생일 경우, 02:20 / 3:52와 같은 형태로 활용할 수 있도록 현재재생시간, 전체재생시간을 제공 -> 해당 건은 currentTime(현재 재생 위치)이랑 duration(음원 총 길이)로 나타낼 수 있을것 같아요!

이부분은 `00:00`형식으로 포맷팅된 형식을 제공하면 간편하게 사용할 수 있지 않을까 했는데 다시 생각해보니 띄어쓰기라던가 포맷팅쪽은 자유롭게 두는게 더 나을 것 같네요😊

2024-08-03 08:40 UTC, foresec commented on src/hooks/useSound.ts
> +  stop: () => void;
[P2] 이 부분 Fn으로 바꿔야할 것 같아요. 관리해야 할 값이 너무 많아서 깜빡하신 듯 합니다

2024-08-03 08:45 UTC, foresec commented on src/hooks/useSound.ts
> +  }
[P3] 다음과 같이 default값으로 자동으로 설정된다는 멘트가 있다면 사용자 입장에서 더 도움이 되지않을까 합니다.

```ts
  const adjustedVolume = Math.min(Math.max(defaultVolume, 0), 1);
  console.warn(`defaultVolume 값(${defaultVolume})이 허용 범위(0.0 ~ 1.0)를 초과하여 기본값 ${adjustedVolume}으로 자동 조정되었습니다.`);
  defaultVolume = adjustedVolume;
```

2024-08-03 09:51 UTC, foresec commented on src/hooks/useSound.ts
> +
[P3] handle함수들에서 옵셔널체이닝을 써봐도 좋을 것 같습니다. 저번에 종찬님이 알려주셨는데.. 결국 코딩스타일 차이라 한번 고려해보시죠

예를 들어, 다음코드를

```ts
   const handlePause = () => {
      if (onPause) onPause();
    };
```
아래와 같은 형태로 바꿀 수 있습니다

```ts
 const handlePause = () => {
      onPause?.();
    };
```


```ts
 const handlePause = () => onPause?.();
```

2024-08-03 12:33 UTC, Choozii commented on src/hooks/useSound.ts
> +
[07754be](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/07754bed3a859215ad5da086bb89f1ed5efd0dbb)

수정해봤어요~!
저는 useReducer는 평상시에 많이 안써서 혹시나 개선할 수 있는 부분이 있다면 또 말씀해주세요!

그리고 리듀서 관련 코드가 길어져서 다른 파일로 분리하면 좋겠다는 생각이 드는데, hooks 내부에 useSoundReducer.ts로 분리하는게 좋을지 아니면 reducer 관련 디렉토리를 만들어야 할지 고민이 되네요. 혹시 리듀서 관련 코드를 다른 파일로 분리해본 경험이 있으신가요?

2024-08-03 12:34 UTC, Choozii commented on src/hooks/useSound.ts
> +  const safeAudioHelper = (action: SafeAudioAction) => {
[07754be](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/07754bed3a859215ad5da086bb89f1ed5efd0dbb)

수정했어요!

2024-08-03 12:34 UTC, Choozii commented on src/hooks/useSound.ts
> +  stop: () => void;
[07754be](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/07754bed3a859215ad5da086bb89f1ed5efd0dbb)
여기서 수정했어요~!

2024-08-03 12:36 UTC, Choozii commented on src/hooks/useSound.ts
> +  }
[234d149](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/234d14922abd6d4f5d0ca5b09a411e6c36c9a775)
좋은 생각입니당
여기에서 문구 수정 되었어요!

2024-08-03 12:37 UTC, Choozii commented on src/hooks/useSound.ts
> +
저는 if문이 개인적으로 쉽게 읽혀서 좋아하는데 옵셔널 체이닝을 선호하시나보네요!
이 방식도 간결하게 쓸 수 있어서 좋은것 같아요~
[f7c5590](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/f7c5590c5aca678cad8f1c0f58b08c81e8578716)
여기서 수정했습니다.

2024-08-03 17:47 UTC, foresec commented on src/hooks/useSound.ts
> +  }, [url]);
[P2] `audioRef.current = null`과 같은 메모리 해제 로직이 따로 구현되지 않은 것 같습니다. 클린업을 통해 audio를 pause하고 해제해도 좋지 않을까요?

2024-08-04 01:25 UTC, Choozii commented on src/hooks/useSound.ts
> +  }, [url]);
[fbc916a](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/fbc916a41854535d24cebe2c61f0e21b153294a7)

cleanUpAudioRef를 만들어서 해제하도록 처리했어욤!

2024-08-04 03:35 UTC, jeongbaebang commented on src/hooks/useSound.ts
> +
저도 현재는 리듀서나 관련 부분에 대해 정해진 규칙이 없어 훅 파일에 배치하고 있습니다. 하지만 폴더 자체를 만들어 관리할지, 아니면 특정 훅 폴더(하나의 훅 폴더에 리듀서 폴더, 타입 폴더 등등) 내부에서 관리할지에 따라 방법이 달라질 것 같습니다. 훅이 점점 많아짐에 따라 각각의 폴더를 어떻게 배치할지에 대해서는 다 같이 논의하여 정하는 방식으로 진행해도 좋을 것 같습니다.

2024-08-04 03:37 UTC, jeongbaebang approved these changes

2024-08-04 03:50 UTC, Choozii commented on src/hooks/useSound.ts
> +
저두 정배님이 말씀하신대로 훅 폴더를 만들어서 내부에 타입이나 리듀서, 테스트 파일 같은걸 배치하는게 좋을것 같아보이네요! 구럼 다음주에 논의해보아욤~!

2024-08-04 07:25 UTC, foresec approved these changes

2024-08-05 01:17 UTC, bicochan requested changes
멋져요 지예 님!

코딩컨벤션 내용 댓글 달았습니다. 확인 부탁드려요!

2024-08-05 01:17 UTC, bicochan commented on src/hooks/useSound.ts
> +type AudioState = {
```suggestion
interface AudioState = {
```
기본으로 interface를 사용하기로 했으니 수정해 볼까요?🤗

2024-08-05 01:17 UTC, bicochan commented on src/hooks/useSound.ts
> +      dispatch({ type: ACTION_TYPES.SET_IS_LOOP, payload: isLoop }),
```suggestion
    setIsLoop(isLoop) {
      dispatch({ type: ACTION_TYPES.SET_IS_LOOP, payload: isLoop })
    }
```
코딩컨벤션 Objects 메서드의 단축 구문!

2024-08-05 08:16 UTC, Choozii commented on src/hooks/useSound.ts
> +      dispatch({ type: ACTION_TYPES.SET_IS_LOOP, payload: isLoop }),
오옹 감사합니다 [a06d001](https://github.com/frontend-opensource-project/use-react-hooks/pull/37/commits/a06d0012e118a0aa928c54f2afbd7483a36546ae) 여기서 수정했어요!

2024-08-06 07:45 UTC, bicochan approved these changes

2024-08-06 13:06 UTC, merged