[URH-48] useGeolocation 신규
frontend-opensource-project/use-react-hooks pull request #45
Opened 2024-08-10 03:30 UTC by Choozii

## 👾 Pull Request

- 티켓: [useGeolocation 신규](https://use-react-hooks.atlassian.net/browse/URH-48)

- 상태: 신규

### 1️⃣ Spec

- 현재 유저의 [지리적 위치](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition) 값 리턴, 위치 불러오기 중인지 로딩 여부, 에러값 리턴
- device 위치가 변경될 때마다 호출되도록 watchPosition() 사용

### 2️⃣ 변경 사항
### 3️⃣ 예시 코드

```ts
const { coords, timestamp, error, loading } = useGeolocation();

  if(loading){
  return <p>loading...</p>
  }

  if(error){
  return <p>{error.message}</p>
  }

  return (
    <div>
          <p>Latitude: {coords.latitude}</p>
          <p>Longitude: {coords.longitude}</p>
          <p>Altitude: {coords.altitude}</p>
          <p>Timestamp: {new Date(timestamp).toLocaleString()}</p>
    </div>
  );
```

### 4️⃣ 관련 문서 (선택 사항)
- https://developer.mozilla.org/en-US/docs/Web/API/Geolocation

2024-08-15 15:16 UTC, foresec reviewed
수고하셨습니다👍 늦게나마 코드리뷰 남겨봐요😂

2024-08-15 15:20 UTC, foresec commented on src/hooks/useGeolocation.ts
> +  const [loading, setLoading] = useState(true);
[P2] 현재 options들이 필수적으로 입력되어야 하는 형태로 작성되어 있는데 생각해두신 의도가 있으신걸까요? 
찾아보니 웹 API에서는 3가지 option들이 기본적으로 optional이고 default값이 존재하고 있어 별도의 의도가 없으시다면 기본값을 설정해두는 것도 좋을 것 같습니다.
```ts
const useGeolocation = (options: PositionOptions = {}): UseGeolocationReturnType => {
```

2024-08-16 01:49 UTC, suhyeoonn commented on src/hooks/useGeolocation.ts
> +    const handleSuccess = (position: GeolocationPosition) => {
[P3] 컴포넌트가 언마운트되기 직전에 `watchPosition`이 실행되면, 컴포넌트가 이미 언마운트되었더라도 `handleSuccess` 또는 `handleError`에서 상태 업데이트를 시도할 것 같아요! `isMounted`와 같은 플래그를 하나 추가하여, 컴포넌트가 마운트된 상태에서만 상태 업데이트가 이루어지도록 하면 메모리 누수를 방지할 수 있을 것 같네요!☺️

```ts
const useGeolocation = (options: PositionOptions) => {
  // ...
  useEffect(() => {
    let isMounted = true;

    const handleSuccess = (position: GeolocationPosition) => {
      if (!isMounted) return; 
      setPosition(position);
      setLoading(false);
    };
    
    return () => {
      isMounted = false; 
      navigator.geolocation.clearWatch(watchId);
    };
}, [...])

2024-08-16 01:49 UTC, suhyeoonn commented on src/hooks/useGeolocation.ts
> + * @returns {UseGeolocationReturnType} - 타임스탬프, 좌표를 포함한 위치 정보와 로딩 여부, 에러 값
[P5] `@param`과 같이 리턴되는 값들 - `coords` 객체 안에 포함된 각 속성(`latitude`, `longitude`, `accuracy` 등)에 대해서도 각각 설명을 적어주시면 훅 사용자가 더욱 쉽게 이해하고 활용할 수 있을 것 같아요!

```
 * @returns {UseGeolocationReturnType.coords} coords - 위치 좌표 객체
 * @returns {number} coords.latitude - 위치의 위도 정보
```

2024-08-17 15:34 UTC, bicochan requested changes

2024-08-17 15:34 UTC, bicochan commented on src/hooks/useGeolocation.ts
> +    timestamp: position?.timestamp ?? undefined,
[P1] 코딩 컨벤션 Destructuring 확인해 주세요!

2024-08-17 15:34 UTC, bicochan commented on src/hooks/useGeolocation.ts
> +      setPosition(null);
[P2] 이 세 줄의 함수를 `handleReset()`과 같은 함수로 정의하는 건 어떠신가요? 함수명에서 의도를 명확하게 드러내면 세 줄의 코드를 읽지 않아도 빠르게 이해할 수 있을 것 같아서요!

2024-08-19 13:51 UTC, Choozii commented on src/hooks/useGeolocation.ts
> +    timestamp: position?.timestamp ?? undefined,
[0b0e440](https://github.com/frontend-opensource-project/use-react-hooks/pull/45/commits/0b0e4407c524ec0ad29ee5a88b74589cc8a75d19)

여기서 변경되었어요!!

2024-08-19 13:51 UTC, Choozii commented on src/hooks/useGeolocation.ts
> +      setPosition(null);
[4bbd65a](https://github.com/frontend-opensource-project/use-react-hooks/pull/45/commits/4bbd65a732c39df4621df651687ac5d42480a080)
여기서 변경되었습니다~

2024-08-19 13:52 UTC, Choozii commented on src/hooks/useGeolocation.ts
> +  const [loading, setLoading] = useState(true);
[f91ff13](https://github.com/frontend-opensource-project/use-react-hooks/pull/45/commits/f91ff13ef2b9dd4887a27c502372ce16347fea33)
여기서 적용했어요!

2024-08-19 13:52 UTC, Choozii commented on src/hooks/useGeolocation.ts
> +    const handleSuccess = (position: GeolocationPosition) => {
오호 이걸 생각못했네여 감사합니다!

[f91ff13](https://github.com/frontend-opensource-project/use-react-hooks/pull/45/commits/f91ff13ef2b9dd4887a27c502372ce16347fea33)에서 반영했어요!

2024-08-19 13:52 UTC, Choozii commented on src/hooks/useGeolocation.ts
> + * @returns {UseGeolocationReturnType} - 타임스탬프, 좌표를 포함한 위치 정보와 로딩 여부, 에러 값
[f91ff13](https://github.com/frontend-opensource-project/use-react-hooks/pull/45/commits/f91ff13ef2b9dd4887a27c502372ce16347fea33)에서 반영되었습니다!

2024-08-20 00:21 UTC, suhyeoonn approved these changes
수고하셨습니다!!🥳

2024-08-21 04:09 UTC, bicochan approved these changes
👍🏻✨

2024-08-21 04:21 UTC, foresec approved these changes
승인을 잊고 있었네요 수고하셨습니다😊

2024-08-21 14:24 UTC, merged