[URH-62] usePermission 신규
frontend-opensource-project/use-react-hooks pull request #49
Opened 2024-08-16 13:28 UTC by jeongbaebang

## 👾 Pull Request

- 티켓: [usePermission 신규](https://use-react-hooks.atlassian.net/jira/software/projects/URH/list?direction=DESC&selectedIssue=URH-62&sortBy=assignee)

- 상태: 신규

### 1️⃣ Spec

- 사용자의 권한 상태를 확인하고 추적하는 커스텀 훅.

### 2️⃣ 변경 사항

- 해당 사항 없음

### 3️⃣ 예시 코드

```ts
import React, { useState } from 'react';
import usePermission from './hooks/usePermission';

const LocationComponent: React.FC = () => {
  const { status } = usePermission({ permission: 'geolocation' });
  const [location, setLocation] = useState<{
    latitude: number;
    longitude: number;
  } | null>(null);

  const handleGetLocation = () => {
    if (status === 'prompt' || status === 'granted') {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setLocation({
            latitude: position.coords.latitude,
            longitude: position.coords.longitude,
          });
        },
        (error) => {
          console.error('위치 정보를 가져오는데 실패했습니다.', error);
        }
      );
    } else {
      alert('위치 정보 권한이 필요합니다.');
    }
  };

  return (
    <div>
      <h2>위치 정보 권한 상태: {status}</h2>
      <button onClick={handleGetLocation}>위치 정보 가져오기</button>
      {location && (
        <div>
          <p>위도: {location.latitude}</p>
          <p>경도: {location.longitude}</p>
        </div>
      )}
      {status === 'prompt' && <p>위치 정보 접근 권한을 요청 중입니다...</p>}
      {status === 'denied' && (
        <p>
          위치 정보 접근 권한이 거부되었습니다. 설정에서 권한을 허용해 주세요.
        </p>
      )}
      {status === 'notSupported' && (
        <p>이 브라우저는 위치 정보 접근 권한을 지원하지 않습니다.</p>
      )}
    </div>
  );
};

export default LocationComponent;

```

### 4️⃣ 관련 문서 (선택 사항)
- https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

2024-08-19 04:17 UTC, foresec reviewed
수고하셨습니다!!👍😊

2024-08-19 04:31 UTC, foresec commented on src/hooks/usePermission.ts
> +  return { status };
[P3] 지금 형태만 봐서는 객체 형태가 아닌 status 하나만 반환해도 충분하지 않을까요? 아니면 또다른 확장성을 고려하고 계신걸까요?

2024-08-19 04:59 UTC, foresec commented on src/hooks/usePermission.ts
> +      });
[P3] 공식문서를 찾아보니 비동기형식으로 받아오는 것 같고, 정배님께서 주로 async-await를 자주 사용하시는 경향을 봐서, 혹시 이번에 then-catch로 작성하신 이유가 따로 있을까요??

2024-08-20 00:32 UTC, suhyeoonn commented on src/hooks/usePermission.ts
> +  return { status };
저도 status 하나만 반환해도 될 것 같은데, 왠지 이번에 정해진 훅의 리턴 타입 관련 컨벤션 맞추기 위해서 그러신 것 같기도 하네요..!👀

2024-08-20 00:33 UTC, suhyeoonn approved these changes
수고하셨습니다😊

2024-08-25 13:07 UTC, jeongbaebang commented on src/hooks/usePermission.ts
> +  return { status };
넵 이번에 컨벤션에 맞춰서 객체 형태로 구성했습니다

2024-08-25 13:13 UTC, jeongbaebang commented on src/hooks/usePermission.ts
> +      });
특별한 이유는 없습니다. async/await 키워드를 사용하거나 asyncWave 라이브러리를 사용할까도 고민해봤지만, 이번에는 then 핸들러를 사용하는 것이 코드가 더 읽기 쉽다고 생각해서 이렇게 작성해 보았습니다.

2024-08-26 07:00 UTC, foresec commented on src/hooks/usePermission.ts
> +  return { status };
그렇군요...!? 저는 리턴값이 하나일 경우엔 interface로 따로 작성하지 않아와서 값이 있다면 인터페이스를 작성해야 하는건지 조금 혼동이 오네요

2024-08-26 07:06 UTC, foresec commented on src/hooks/usePermission.ts
> +      });
앗 저는 어떤 가독성의 이유라기보단 평소 스타일?과는 다른 선택을 하신거 같아 혹시 특별한 이유가 있나 궁금해서 물어본 것이었습니다ㅋㅋ  개인적인 의견으로는 제안주신 방식들이 다 괜찮아 보여서 정배님께서 원하시는 방식으로 자유롭게 선택하시는게 가장 좋은 것 같습니다.

2024-08-26 07:06 UTC, foresec approved these changes
수고하셨습니다🚀🚀

2024-08-26 07:53 UTC, jeongbaebang commented on src/hooks/usePermission.ts
> +  return { status };
생각해 보니 그러네요 값을 하나만 리턴하는 경우에는 어떻게 해야 할지 논의해 보면 좋겠네요!

2024-08-29 12:18 UTC, bicochan requested changes

2024-08-29 12:18 UTC, bicochan commented on src/hooks/usePermission.ts
> +      });
[P1] `then/catch` 문을 사용하신 이유가 특별히 없으시다면 다른 훅들과 스타일을 맞추는 게 좋을 것 같습니다! `async/await`로 컨벤션을 정할까요?!

2024-08-29 17:32 UTC, jeongbaebang commented on src/hooks/usePermission.ts
> +      });
넵 좋습니다. 리뷰 반영해서 커밋 올리겠습니다

2024-09-01 10:24 UTC, jeongbaebang commented on src/hooks/usePermission.ts
> +      });
[commit] https://github.com/frontend-opensource-project/use-react-hooks/pull/49/commits/27690de65f2f536b2807caddfe746a81b8e8373c

@bicochan  반영했습니다.

2024-09-06 13:48 UTC, bicochan approved these changes

2024-09-06 13:49 UTC, merged