[URH-81] useKeyCombination 문서 작성
frontend-opensource-project/use-react-hooks pull request #69
Opened 2024-09-16 21:53 UTC by suhyeoonn

## 👾 Pull Request

- 티켓: [useKeyCombination 문서 작성](https://use-react-hooks.atlassian.net/browse/URH-81)

- 상태: 문서

훅의 리턴 값이 없어서 _없음_ 으로 기재했는데, 괜찮을지 확인 부탁드려요~!
<img width="1604" alt="image" src="https://github.com/user-attachments/assets/9616c7cb-df57-470d-b5b5-69817368358b">

2024-09-20 14:43 UTC, bicochan requested changes
고생하셨어요 수현 님!👍🏻✨ 코딩컨벤션 확인 부탁드려요~

2024-09-20 14:43 UTC, bicochan commented on docs/pages/docs/hooks/useKeyCombination.mdx
> +interface UseKeyCombination {
```suggestion
interface UseKeyCombinationProps {
```
[P1] 코딩컨벤션 Interface 부분 확인 부탁드려요!

2024-09-20 14:43 UTC, bicochan commented on docs/pages/docs/hooks/useKeyCombination.mdx
> +
Return 값이 없다면 제거해도 괜찮을 것 같습니다!

2024-09-21 09:07 UTC, suhyeoonn commented on docs/pages/docs/hooks/useKeyCombination.mdx
> +
제거하였습니다~! 
[commit] [e327366](https://github.com/frontend-opensource-project/use-react-hooks/pull/69/commits/e32736644f0dcc0df3766168469df2c2c6bbcecf)

2024-10-08 00:58 UTC, merged